#
# Module manifest for module 'BuildMatrix'
#
# Generated by: craig.gumbley
#
# Generated on: 07/11/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'BuildMatrix.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '90b4bad9-acaf-454a-8eb9-1430a5a2edcc'

# Author of this module
Author = 'Puppet'

# Company or vendor of this module
CompanyName = 'Puppet'

# Copyright statement for this module
Copyright = '(c) Puppet. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Helpers for generating a build matrix for use with Puppet.Dsc workflows.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'PowerShell-Yaml',
    'Puppet.Dsc'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'ConvertTo-BuildMatrix',
    'Get-ModuleData',
    'Set-BuildMatrix'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{}
    }
}

